// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeq1HKDiBznOB3U1VQ0DmFUnMsEtFa4XE',
    appId: '1:518261146132:web:03f40c7f400c5ee2031d01',
    messagingSenderId: '518261146132',
    projectId: 'uwu-wireless',
    authDomain: 'uwu-wireless.firebaseapp.com',
    storageBucket: 'uwu-wireless.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuFp2V77uo9k5Us3EHsCdtKcI9lGtKgok',
    appId: '1:518261146132:android:27cba0985d2c9cfe031d01',
    messagingSenderId: '518261146132',
    projectId: 'uwu-wireless',
    storageBucket: 'uwu-wireless.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3ocP18wHmgXQmyYMFRW-NN1s3sJ11BJo',
    appId: '1:518261146132:ios:376fcd0a5d7b84df031d01',
    messagingSenderId: '518261146132',
    projectId: 'uwu-wireless',
    storageBucket: 'uwu-wireless.appspot.com',
    iosBundleId: 'com.example.uwuAppV3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3ocP18wHmgXQmyYMFRW-NN1s3sJ11BJo',
    appId: '1:518261146132:ios:20bc3cf17ee735af031d01',
    messagingSenderId: '518261146132',
    projectId: 'uwu-wireless',
    storageBucket: 'uwu-wireless.appspot.com',
    iosBundleId: 'com.example.uwuAppV3.RunnerTests',
  );
}
